"""Export video insights to Markdown."""

from __future__ import annotations

import json
from datetime import datetime, timezone

import db


def _parse_structured(raw: str | dict | None) -> dict | None:
    if not raw:
        return None
    if isinstance(raw, dict):
        return raw
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return None


def _format_ts_link(video_id: str, seconds: int | float | None) -> str:
    if seconds is None:
        return ""
    sec = int(seconds)
    m, s = divmod(sec, 60)
    h, m = divmod(m, 60)
    label = f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"
    url = f"https://www.youtube.com/watch?v={video_id}&t={sec}s"
    return f" ([{label}]({url}))"


def export_video_markdown(video: dict) -> str:
    """Generate Markdown from a processed video DB row."""
    lines: list[str] = []
    title = video.get("title", "Untitled")
    channel = video.get("channel_name", "Unknown channel")
    video_id = video.get("video_id", "")
    playlist_type = video.get("playlist_type", "general")
    yt_url = video.get("url") or f"https://www.youtube.com/watch?v={video_id}"

    lines.extend([
        f"# {title}",
        "",
        f"**Channel:** {channel}  ",
        f"**Type:** {playlist_type.title()}  ",
        f"**Source:** [{yt_url}]({yt_url})  ",
        f"**Extracted:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}  ",
        "",
        "---",
        "",
    ])

    summary = video.get("summary", "")
    if summary:
        lines.extend(["## Summary", "", summary, ""])

    structured = _parse_structured(video.get("structured_insights"))
    if structured:
        guest = structured.get("guest_profile")
        if guest and isinstance(guest, dict):
            lines.extend(["## Guest", ""])
            name = guest.get("name") or guest.get("background", "")
            if guest.get("name"):
                lines.append(f"**{guest['name']}**")
            if guest.get("background"):
                lines.append(f"  {guest['background']}")
            for ach in guest.get("notable_achievements") or []:
                lines.append(f"- {ach}")
            lines.append("")

        insights = structured.get("insights", [])
        if insights:
            lines.extend(["## Key Insights", ""])
            for i, ins in enumerate(insights, 1):
                ins_title = ins.get("topic") or ins.get("title") or f"Insight {i}"
                ts_str = _format_ts_link(video_id, ins.get("timestamp_seconds"))
                lines.append(f"### {i}. {ins_title}{ts_str}")
                lines.append("")
                content = ins.get("content") or ""
                points = ins.get("points") or []
                if content:
                    lines.append(content)
                for pt in points:
                    lines.append(f"- {pt}")
                tags = ins.get("tags") or []
                if tags:
                    lines.append(f"*Tags: {', '.join(tags)}*")
                lines.append("")

        resources = structured.get("resources", [])
        if resources:
            lines.extend(["## Resources Mentioned", ""])
            for res in resources:
                name = res.get("name", "")
                rtype = res.get("type", "")
                url = res.get("url")
                if url:
                    lines.append(f"- **{name}** ({rtype}) — [{url}]({url})")
                else:
                    lines.append(f"- **{name}** ({rtype})")
            lines.append("")

        links = structured.get("links", {})
        if links:
            lines.extend(["## Links", ""])
            for group_name, group_links in links.items():
                if not group_links:
                    continue
                lines.append(f"### {group_name.replace('_', ' ').title()}")
                lines.append("")
                for link in group_links:
                    if isinstance(link, dict):
                        url = link.get("url", "")
                        title_l = link.get("title") or url
                        if url:
                            lines.append(f"- [{title_l}]({url})")
                    elif isinstance(link, str):
                        lines.append(f"- {link}")
                lines.append("")

    agenda = video.get("auto_agenda", "")
    if agenda:
        lines.extend(["## Agenda", "", agenda, ""])

    lines.extend(["---", "", "*Generated by YouTube Insight Agent*"])
    return "\n".join(lines)
