"""
Part E, step 3 — the photo library and the photo pick.

Reference video 1 handles this with descriptive filenames ("balcony-ocean-coffee")
so the model can guess which photo suits a post. That works for a personal brand.
For a dental practice it is not enough, because a photo can contain a patient and
that carries a written-release requirement. So the library is a manifest, not a
naming convention, and every entry records consent state.

The manifest is generated by scanning the folder; you then fill in descriptions
once. `assets.py scan` is idempotent and never overwrites a description you wrote.

See DECISIONS.md D-27.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # -> content-engine/

from shared import llm  # noqa: E402
from shared.config import ClientProfile  # noqa: E402

HERE = Path(__file__).resolve().parent
PHOTO_DIR = HERE / "assets" / "photos"
MANIFEST = HERE / "assets" / "photos.json"

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}

PICK_PROMPT = """Pick the best photo to sit behind the cover text of a carousel.

WHAT THE COVER SAYS:
  headline: {headline}
  subtext:  {subtext}
  brief:    {brief}

AVAILABLE PHOTOS:
{photos}

Return JSON:
{{"photo_id": "the id of the photo you picked",
  "why": "one sentence",
  "text_position": "top" | "bottom" | "center",
  "scrim": "light" | "dark",
  "second_choice": "id of a runner-up, or empty"}}

Rules:
- Pick for MEANING first, composition second. A photo of the actual room the
  post is about beats a prettier unrelated one.
- text_position must sit where the photo is emptiest, so the text stays legible.
- scrim "dark" darkens the photo for white text; "light" lightens it for dark text.
  Choose based on how bright the photo is where the text will sit.
- Never pick a photo whose consent field is anything other than "not_applicable"
  or "on_file"."""


def scan(photo_dir: Path = PHOTO_DIR, manifest_path: Path = MANIFEST) -> dict[str, Any]:
    """Add any new image files to the manifest without touching existing entries."""
    photo_dir.mkdir(parents=True, exist_ok=True)
    data: dict[str, Any] = {"photos": []}
    if manifest_path.exists():
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    known = {p["file"] for p in data.get("photos", [])}

    added = 0
    for f in sorted(photo_dir.iterdir()):
        if f.suffix.lower() not in IMAGE_SUFFIXES or f.name in known:
            continue
        entry: dict[str, Any] = {
            "id": f.stem,
            "file": f.name,
            "description": "",          # fill this in - it drives the pick
            "tags": [],
            "depicts_patient": False,
            "subject_ref": "",
            "consent": "not_applicable",  # not_applicable | on_file | missing
            "orientation": "",
            "bright_area": "",           # where the photo is lightest: top/bottom/left/right
        }
        try:
            from PIL import Image

            with Image.open(f) as im:
                w, h = im.size
                entry["orientation"] = (
                    "portrait" if h > w * 1.1 else "landscape" if w > h * 1.1 else "square"
                )
                entry["size"] = [w, h]
        except Exception:  # noqa: BLE001
            pass
        data["photos"].append(entry)
        added += 1

    data["_note"] = (
        "Fill in 'description' for every photo - it is what the picker reads. "
        "Set depicts_patient/subject_ref/consent for anything showing a patient; "
        "publishing is blocked unless a matching release is in the consent register."
    )
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"added": added, "total": len(data["photos"]), "path": str(manifest_path)}


def load_manifest(manifest_path: Path = MANIFEST) -> list[dict[str, Any]]:
    if not manifest_path.exists():
        return []
    return json.loads(manifest_path.read_text(encoding="utf-8")).get("photos", [])


def usable(photos: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Drop anything that cannot lawfully be published without a release."""
    out = []
    for p in photos:
        if p.get("depicts_patient") and p.get("consent") != "on_file":
            continue
        out.append(p)
    return out


def pick_photo(
    cover: dict[str, Any],
    photo_brief: str,
    *,
    manifest_path: Path = MANIFEST,
) -> dict[str, Any] | None:
    """Choose a background photo for the cover. Returns None if none are usable."""
    photos = usable(load_manifest(manifest_path))
    if not photos:
        return None

    described = [p for p in photos if (p.get("description") or "").strip()]
    pool = described or photos

    if len(pool) == 1:
        p = pool[0]
        return {"photo": p, "text_position": "bottom", "scrim": "dark",
                "why": "only usable photo in the library"}

    listing = "\n".join(
        f"- id: {p['id']}\n  description: {p.get('description') or '(none)'}\n"
        f"  tags: {', '.join(p.get('tags', []))}\n"
        f"  orientation: {p.get('orientation','')}  bright_area: {p.get('bright_area','')}\n"
        f"  consent: {p.get('consent','not_applicable')}"
        for p in pool
    )
    try:
        choice = llm.ask_json(
            PICK_PROMPT.format(
                headline=cover.get("headline", ""),
                subtext=cover.get("subtext", ""),
                brief=photo_brief or "(none given)",
                photos=listing,
            )
        )
    except Exception:  # noqa: BLE001
        choice = {}

    by_id = {p["id"]: p for p in pool}
    chosen = by_id.get(choice.get("photo_id", "")) or pool[0]
    return {
        "photo": chosen,
        "text_position": choice.get("text_position", "bottom"),
        "scrim": choice.get("scrim", "dark"),
        "why": choice.get("why", "fallback: first usable photo"),
        "second_choice": choice.get("second_choice", ""),
    }


def as_data_uri(path: Path) -> str:
    """Inline the photo so the rendered HTML is self-contained."""
    import base64
    import mimetypes

    mime = mimetypes.guess_type(path.name)[0] or "image/jpeg"
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{b64}"


if __name__ == "__main__":
    print(json.dumps(scan(), indent=2))
